---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Proxmox headers, DKMS, and initramfs-tools
  ansible.builtin.apt:
    name:
      - pve-headers
      - dkms
      - initramfs-tools
    state: present
  register: package_install_result

- name: Reboot the host if packages were installed
  ansible.builtin.reboot:
  when: package_install_result.changed
