---
- name: Ensure NVIDIA rules are present
  ansible.builtin.copy:
    src: 70-nvidia.rules
    dest: /etc/udev/rules.d/70-nvidia.rules
    mode: "0644"
    owner: root
    group: root
  register: rules_result

- name: Add NVIDIA and nvidia_uvm to modules
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/modules.conf
    block: |
      nvidia
      nvidia_uvm
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  register: modules_result

- name: Update initramfs # noqa no-handler
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  when: rules_result.changed or modules_result.changed
