---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install proxmox headers and dkms
  ansible.builtin.apt:
    name:
      - pve-headers
      - dkms
      - initramfs-tools
    state: present
  register: package_install_result

- name: Reboot host # noqa no-handler
  ansible.builtin.reboot:
  when: package_install_result.changed
