---
- name: Ensure NVIDIA rules are present
  ansible.builtin.copy:
    src: 70-nvidia.rules
    dest: /etc/udev/rules.d/70-nvidia.rules
    mode: "0644"
    owner: root
    group: root

- name: Add NVIDIA and nvidia_uvm to modules
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/modules.conf
    block: |
      nvidia
      nvidia_uvm
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  when: "'Driver Version' not in nvidia_result.stdout"

- name: Ensure NVIDIA persistence daemon is enabled
  ansible.builtin.service:
    name: nvidia-persistenced
    enabled: true
    state: started
