---
- name: Ensure NVIDIA udev rules are present
  ansible.builtin.copy:
    src: 70-nvidia.rules
    dest: /etc/udev/rules.d/70-nvidia.rules
    mode: "0644"
    owner: root
    group: root
  register: rules_result

- name: Ensure NVIDIA and VFIO modules are added to modules-load
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/modules.conf
    block: |
      nvidia
      nvidia_uvm
      nvidia_modeset
      nvidia_drm
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NVIDIA Modules"
  register: modules_result

- name: Update initramfs if rules or modules were changed
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  when: rules_result.changed or modules_result.changed
