---
# tasks file for ansible-lxc-nvidia
- name: Ensure NVIDIA installer is present
  ansible.builtin.get_url:
    url: "https://us.download.nvidia.com/XFree86/Linux-x86_64/{{ lxc_nvidia_version }}/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run"
    dest: "/root/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run"
    mode: "0755"
    owner: root
    group: root

- name: Check if NVIDIA is installed
  ansible.builtin.command: "nvidia-smi"
  register: nvidia_result
  failed_when: false
  changed_when: false

- name: Run host specific pre-install tasks
  ansible.builtin.include_tasks: host-pre.yml
  when: lxc_nvidia_is_host

- name: Run NVIDIA installer
  ansible.builtin.command: "/root/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run -asq {{ lxc_nvidia_is_host and '' or '--no-kernel-module' }}"
  changed_when: true
  when: "'Driver Version' not in nvidia_result.stdout or lxc_nvidia_version not in nvidia_result.stdout"
  register: nvidia_install_result

- name: Run host specific tasks
  ansible.builtin.include_tasks: host.yml
  when: lxc_nvidia_is_host

- name: Reboot host
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: nvidia_install_result.changed

- name: Run NVIDIA patch
  ansible.builtin.command: /root/patch.sh
  changed_when: true
  when: nvidia_install_result.changed

- name: Update lxc config
  ansible.builtin.include_tasks: update-conf.yml
