---
# tasks file for ansible-lxc-nvidia
- name: Get NVIDIA patch script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/keylase/nvidia-patch/master/patch.sh
    dest: /root/patch.sh
    mode: "0755"
    owner: root
    group: root

- name: Ensure NVIDIA installer is present
  ansible.builtin.get_url:
    url: "https://us.download.nvidia.com/XFree86/Linux-x86_64/{{ lxc_nvidia_version }}/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run"
    dest: "/root/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run"
    mode: "0755"
    owner: root
    group: root

- name: Check if NVIDIA is installed
  ansible.builtin.command: "nvidia-smi"
  register: nvidia_result
  failed_when: false
  changed_when: false

- name: Run host specific pre-install tasks
  ansible.builtin.include_tasks: host-pre.yml
  when: lxc_nvidia_is_host

- name: Run NVIDIA installer
  ansible.builtin.command: "/root/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run -asq {{ lxc_nvidia_is_host | ternary('', '--no-kernel-module') }}"
  changed_when: true
  when: "lxc_nvidia_version not in nvidia_result.stdout"
  failed_when: false
  register: nvidia_install_result

- name: Reboot if NVIDIA installation changed
  ansible.builtin.reboot:
  when: nvidia_install_result.changed or "failed" in nvidia_install_result

- name: Retry NVIDIA installation if it failed
  ansible.builtin.command: "/root/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run -asq {{ lxc_nvidia_is_host | ternary('', '--no-kernel-module') }}"
  changed_when: true
  when: '"failed" in nvidia_install_result'
  failed_when: false
  register: nvidia_install_result

- name: Run host specific tasks
  ansible.builtin.include_tasks: host.yml
  when: lxc_nvidia_is_host

- name: Reboot after installation if there were changes
  ansible.builtin.reboot:
  when: nvidia_install_result.changed

- name: Run NVIDIA installer again if needed
  ansible.builtin.command: "/root/NVIDIA-Linux-x86_64-{{ lxc_nvidia_version }}.run -asq {{ lxc_nvidia_is_host | ternary('', '--no-kernel-module') }}"
  changed_when: true
  when: "lxc_nvidia_version not in nvidia_result.stdout"

- name: Run NVIDIA patch script
  ansible.builtin.command: /root/patch.sh
  register: nvidia_patch_result
  changed_when: "'Patched!' in nvidia_patch_result.stdout"
  when: nvidia_install_result.changed

- name: Update LXC configuration
  ansible.builtin.include_tasks: update-conf.yml
  when: lxc_nvidia_is_host
